services:
  postgres:
    image: postgres:latest
    container_name: questionservicepostgresql
    restart: always
    environment:
      - POSTGRES_PASSWORD=P455w0rd.
      - POSTGRES_USER=user
      - POSTGRES_DB=questionservicedb
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - ./postgresql/database/data:/var/lib/postgresql/data
